global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'devpulse-backend-prod'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['devpulse-frontend-kg5k.onrender.com'] # IMPORTANT: Replace with your actual Render backend domain (without https://)
